specs = ['Physical Therapist in Private Practice',
 'Clinical Laboratory',
 'Orthopedic Surgery',
 'Anesthesiology Assistant',
 'Obstetrics & Gynecology',
 'Cardiology',
 'Optometry',
 'Infectious Disease',
 'Nephrology',
 'Pulmonary Disease',
 'Mass Immunizer Roster Biller',
 'Certified Registered Nurse Anesthetist (CRNA)',
 'Diagnostic Radiology',
 'Pathology',
 'Family Practice',
 'Nurse Practitioner',
 'General Surgery',
 'Chiropractic',
 'Internal Medicine',
 'Anesthesiology',
 'Otolaryngology',
 'Emergency Medicine',
 'Plastic and Reconstructive Surgery',
 'Ambulance Service Provider',
 'Psychologist, Clinical',
 'Dermatology',
 'Physician Assistant',
 'Hematology-Oncology',
 'Medical Oncology',
 'Occupational Therapist in Private Practice',
 'Physical Medicine and Rehabilitation',
 'Endocrinology',
 'Neurology',
 'Neurosurgery',
 'Psychiatry',
 'Hospice and Palliative Care',
 'Ambulatory Surgical Center',
 'Licensed Clinical Social Worker',
 'Ophthalmology',
 'Thoracic Surgery',
 'Hospitalist',
 'Critical Care (Intensivists)',
 'Podiatry',
 'Audiologist',
 'Pharmacy',
 'Centralized Flu',
 'Radiation Oncology',
 'Rheumatology',
 'Gastroenterology',
 'Certified Nurse Midwife',
 'Interventional Pain Management',
 'Medical Toxicology',
 'Allergy/ Immunology',
 'Gynecological Oncology',
 'Colorectal Surgery (Proctology)',
 'Urology',
 'Independent Diagnostic Testing Facility (IDTF)',
 'Opioid Treatment Program',
 'Speech Language Pathologist',
 'Interventional Radiology',
 'Hand Surgery',
 'Mammography Center',
 'Oral Surgery (Dentist only)',
 'General Practice',
 'Cardiac Surgery',
 'Advanced Heart Failure and Transplant Cardiology',
 'Vascular Surgery',
 'Pain Management',
 'Osteopathic Manipulative Medicine',
 'Pediatric Medicine',
 'Micrographic Dermatologic Surgery',
 'Interventional Cardiology',
 'Certified Clinical Nurse Specialist',
 'Clinical Cardiac Electrophysiology',
 'Surgical Oncology',
 'Geriatric Medicine',
 'Registered Dietitian or Nutrition Professional',
 'Clinic or Group Practice',
 'Sleep Medicine',
 'Nuclear Medicine',
 'Sports Medicine',
 'Addiction Medicine',
 'Hematology',
 'Medicare Diabetes Preventive Program',
 'Neuropsychiatry',
 'Undefined Physician type',
 'Portable X-Ray Supplier',
 'Maxillofacial Surgery',
 'Geriatric Psychiatry',
 'Public Health or Welfare Agency',
 'Hematopoietic Cell Transplantation and Cellular Therapy',
 'Dentist',
 'All Other Suppliers',
 'Preventive Medicine',
 'Undersea and Hyperbaric Medicine',
 'Unknown Supplier/Provider Specialty',
 'Slide Preparation Facility',
 'Medical Genetics and Genomics',
 'Radiation Therapy Center',
 'Adult Congenital Heart Disease',
 'Peripheral Vascular Disease',
 'Home Infusion Therapy Services']

states=['NY', 'LA',
 'AL',
 'FL',
 'NC',
 'MA',
 'SC',
 'CA',
 'TX',
 'GA',
 'AK',
 'WV',
 'PA',
 'MN',
 'CO',
 'CT',
 'IL',
 'KS',
 'OH',
 'ID',
 'UT',
 'AZ',
 'MI',
 'VA',
 'NE',
 'MO',
 'TN',
 'IN',
 'NJ',
 'OR',
 'WI',
 'WA',
 'MT',
 'MD',
 'SD',
 'NV',
 'KY',
 'MS',
 'VT',
 'ND',
 'IA',
 'NM',
 'AR',
 'NH',
 'RI',
 'DE',
 'ME',
 'WY',
 'OK',
 'HI',
 'DC',
 'PR',
 'AP',
 'GU',
 'VI',
 'MP',
 'AE',
 'ZZ',
 'XX',
 'AA']